# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link_to_upper_base_link
      - upper_base_link_to_lower_link
      - lower_link_to_upper_link
    action_ns: follow_joint_trajectory
  hand_controller:
    type: GripperCommand
    joints:
      - left_finger_joint
    action_ns: gripper_cmd
    default: true