# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: parallel_gripper_action_controller/GripperActionController # <-- Changed this line


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_link_to_upper_base_link
      - upper_base_link_to_lower_link
      - lower_link_to_upper_link
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
hand_controller:
  ros__parameters:
    joint: left_finger_joint
    # Note: The parallel_gripper_controller might require additional parameters
    # depending on your specific gripper setup (e.g., command/state interfaces if not default).
    # Check its documentation if you encounter issues after this change.
    # Default command interface is 'position', state is 'position'.