# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # --- Parameters for UnoStepperInterface ---
    # Add these lines here
    serial_port: "/dev/ttyACM0"  # *** IMPORTANT: Verify this is the correct port ***
    baud_rate: 115200            # Match the baud rate in your Arduino sketch



    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_link_to_upper_base_link
      - upper_base_link_to_lower_link
      - lower_link_to_upper_link
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
hand_controller:
  ros__parameters:
    joint: left_finger_joint